/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface PostNonActor {
  'title' : string,
  'body' : string,
  'published' : boolean,
  'createdAt' : timestamp,
  'tags' : Array<string>,
  'updatedAt' : timestamp,
}
export interface PostPayload {
  'title' : string,
  'body' : string,
  'published' : boolean,
  'tags' : Array<string>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type timestamp = bigint;
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPost' : ActorMethod<[PostPayload], bigint>,
  'deletePost' : ActorMethod<[bigint], undefined>,
  'getAllPosts' : ActorMethod<[], Array<[bigint, PostNonActor]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDraftPosts' : ActorMethod<[], Array<[bigint, PostNonActor]>>,
  'getPost' : ActorMethod<[bigint], PostNonActor>,
  'getPublishedPosts' : ActorMethod<[], Array<[bigint, PostNonActor]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeSamplePosts' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePost' : ActorMethod<[bigint, PostPayload], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];