/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostPayload = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
});
export const timestamp = IDL.Int;
export const PostNonActor = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'updatedAt' : timestamp,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPost' : IDL.Func([PostPayload], [IDL.Nat], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getAllPosts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PostNonActor))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDraftPosts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PostNonActor))],
      ['query'],
    ),
  'getPost' : IDL.Func([IDL.Nat], [PostNonActor], ['query']),
  'getPublishedPosts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, PostNonActor))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeSamplePosts' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePost' : IDL.Func([IDL.Nat, PostPayload], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostPayload = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
  });
  const timestamp = IDL.Int;
  const PostNonActor = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'updatedAt' : timestamp,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPost' : IDL.Func([PostPayload], [IDL.Nat], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getAllPosts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PostNonActor))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDraftPosts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PostNonActor))],
        ['query'],
      ),
    'getPost' : IDL.Func([IDL.Nat], [PostNonActor], ['query']),
    'getPublishedPosts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, PostNonActor))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeSamplePosts' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePost' : IDL.Func([IDL.Nat, PostPayload], [], []),
  });
};

export const init = ({ IDL }) => { return []; };